/**
 * AUTO-GENERATED KEY TEST
 * 
 * Tests that the server auto-generates idempotency keys when not provided:
 * 1. Same inputs produce same auto-generated key
 * 2. Different inputs produce different keys
 * 3. Dashboard can fetch and display executions
 */

const SERVER_URL = 'http://127.0.0.1:3030';
const TEST_PREFIX = 'auto-key-test';

let testsPassed = 0;
let testsFailed = 0;

async function call(method, params) {
  const response = await fetch(SERVER_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      jsonrpc: '2.0',
      method,
      params,
      id: Math.random().toString(36)
    })
  });
  const result = await response.json();
  if (result.error) {
    throw new Error(result.error.message);
  }
  return result.result;
}

async function setup() {
  console.log('Setting up test user and session...\n');
  
  const user = await call('create_user', { username: `${TEST_PREFIX}-${Date.now()}` });
  const session = await call('create_session', { user_id: user.id });
  const goal = await call('create_goal', { 
    user_id: user.id, 
    session_id: session.id, 
    title: 'Auto Key Test Goal' 
  });
  
  return { user, session, goal };
}

async function testAutoGeneratedKey() {
  console.log('TEST 1: Auto-generated key is created when not provided');
  console.log('=========================================================\n');
  
  const { user, session, goal } = await setup();
  
  // Execute WITHOUT providing idempotency_key
  const exec1 = await call('execute_tool_idempotent', {
    user_id: user.id,
    session_id: session.id,
    goal_id: goal.id,
    tool_name: 'test_tool',
    tool_input: { test: 'data' }
    // No idempotency_key provided - server should auto-generate
  });
  
  console.log('Execution created:', exec1.id);
  console.log('Idempotency key:', exec1.idempotency_key);
  
  if (!exec1.idempotency_key) {
    throw new Error('FAIL: No idempotency key generated!');
  }
  
  if (!exec1.idempotency_key.startsWith('auto:')) {
    throw new Error('FAIL: Key should start with "auto:"');
  }
  
  console.log('PASS: Auto-generated key created\n');
  testsPassed++;
  
  return { user, session, goal, exec1 };
}

async function testSameInputsSameKey() {
  console.log('TEST 2: Same inputs produce same auto-generated key');
  console.log('=====================================================\n');
  
  const { user, session, goal } = await setup();
  
  // Call twice with SAME inputs (no key provided)
  const exec1 = await call('execute_tool_idempotent', {
    user_id: user.id,
    session_id: session.id,
    goal_id: goal.id,
    tool_name: 'web_search',
    tool_input: { query: 'rust programming' }
  });
  
  const exec2 = await call('execute_tool_idempotent', {
    user_id: user.id,
    session_id: session.id,
    goal_id: goal.id,
    tool_name: 'web_search',
    tool_input: { query: 'rust programming' }
  });
  
  console.log('First call execution ID:', exec1.id);
  console.log('Second call execution ID:', exec2.id);
  
  if (exec1.id !== exec2.id) {
    throw new Error('FAIL: Same inputs should return same execution!');
  }
  
  console.log('PASS: Same inputs return same execution (no duplicate)\n');
  testsPassed++;
}

async function testDifferentInputsDifferentKey() {
  console.log('TEST 3: Different inputs produce different keys');
  console.log('=================================================\n');
  
  const { user, session, goal } = await setup();
  
  const exec1 = await call('execute_tool_idempotent', {
    user_id: user.id,
    session_id: session.id,
    goal_id: goal.id,
    tool_name: 'api_call',
    tool_input: { endpoint: '/users' }
  });
  
  const exec2 = await call('execute_tool_idempotent', {
    user_id: user.id,
    session_id: session.id,
    goal_id: goal.id,
    tool_name: 'api_call',
    tool_input: { endpoint: '/posts' }
  });
  
  console.log('First execution ID:', exec1.id);
  console.log('Second execution ID:', exec2.id);
  
  if (exec1.id === exec2.id) {
    throw new Error('FAIL: Different inputs should create different executions!');
  }
  
  console.log('PASS: Different inputs create different executions\n');
  testsPassed++;
}

async function testDashboardDataFetch() {
  console.log('TEST 4: Dashboard can fetch session and execution data');
  console.log('========================================================\n');
  
  const { user, session, goal } = await setup();
  
  // Create some executions
  await call('execute_tool_idempotent', {
    user_id: user.id,
    session_id: session.id,
    goal_id: goal.id,
    tool_name: 'read_file',
    tool_input: { path: '/test.txt' }
  });
  
  await call('execute_tool_idempotent', {
    user_id: user.id,
    session_id: session.id,
    goal_id: goal.id,
    tool_name: 'write_file',
    tool_input: { path: '/output.txt', content: 'hello' }
  });
  
  // Fetch sessions (dashboard would call this)
  const sessions = await call('list_sessions', { user_id: user.id });
  console.log('Sessions found:', sessions.length);
  
  // Fetch goals for session (dashboard would call this)
  const goals = await call('list_pending_goals', { session_id: session.id });
  console.log('Goals found:', goals.length);
  
  // Fetch executions for goal (dashboard would call this)
  const executions = await call('list_tool_executions', { goal_id: goal.id });
  console.log('Executions found:', executions.length);
  
  // Verify all executions have auto-generated keys
  for (const exec of executions) {
    if (!exec.idempotency_key || !exec.idempotency_key.startsWith('auto:')) {
      throw new Error('FAIL: Execution should have auto-generated key');
    }
  }
  
  console.log('PASS: Dashboard can fetch all data with auto-generated keys\n');
  testsPassed++;
}

async function testCustomKeyStillWorks() {
  console.log('TEST 5: Custom idempotency key still works when provided');
  console.log('==========================================================\n');
  
  const { user, session, goal } = await setup();
  
  const exec1 = await call('execute_tool_idempotent', {
    user_id: user.id,
    session_id: session.id,
    goal_id: goal.id,
    tool_name: 'send_email',
    tool_input: { to: 'test@example.com' },
    idempotency_key: 'my-custom-key-123'
  });
  
  const exec2 = await call('execute_tool_idempotent', {
    user_id: user.id,
    session_id: session.id,
    goal_id: goal.id,
    tool_name: 'send_email',
    tool_input: { to: 'test@example.com' },
    idempotency_key: 'my-custom-key-123'
  });
  
  console.log('Custom key used:', exec1.idempotency_key);
  
  if (exec1.id !== exec2.id) {
    throw new Error('FAIL: Custom key should work as before!');
  }
  
  if (exec1.idempotency_key !== 'my-custom-key-123') {
    throw new Error('FAIL: Custom key should be preserved!');
  }
  
  console.log('PASS: Custom keys still work correctly\n');
  testsPassed++;
}

async function runTests() {
  console.log('\n');
  console.log('╔════════════════════════════════════════════════════════════╗');
  console.log('║     AUTO-GENERATED IDEMPOTENCY KEY TESTS                  ║');
  console.log('╚════════════════════════════════════════════════════════════╝');
  console.log('\n');
  
  try {
    await testAutoGeneratedKey();
    await testSameInputsSameKey();
    await testDifferentInputsDifferentKey();
    await testDashboardDataFetch();
    await testCustomKeyStillWorks();
    
    console.log('\n');
    console.log('╔════════════════════════════════════════════════════════════╗');
    console.log('║                      RESULTS                              ║');
    console.log('╚════════════════════════════════════════════════════════════╝');
    console.log(`\n✅ PASSED: ${testsPassed}`);
    console.log(`❌ FAILED: ${testsFailed}`);
    console.log('\n');
    
    if (testsFailed > 0) {
      process.exit(1);
    }
    
    console.log('All tests passed! Auto-generated idempotency keys work correctly.\n');
    
  } catch (error) {
    console.error('\n❌ TEST FAILED:', error.message);
    console.error(error.stack);
    process.exit(1);
  }
}

runTests();
