/**
 * OpenClaw Integration for Open Engine
 * 
 * Wraps OpenClaw tool calls with persistent state and idempotency.
 * 
 * Usage:
 *   const agent = new OpenClawAgent({
 *     userId: 'doremon',
 *     engineUrl: 'http://127.0.0.1:3030',
 *     openclawUrl: 'http://127.0.0.1:18789',
 *     openclawToken: 'YOUR_TOKEN'
 *   });
 * 
 *   await agent.init();
 *   const result = await agent.execute('web_search', { query: 'rust' });
 */

import { StateEngineClient } from '../../ts-client/src/client';
import type { ToolExecution, Goal, Session, ToolExecutionStatus } from '../../ts-client/src/types';

type ToolName = 'web_search' | 'web_fetch' | 'exec' | 'read' | 'write' | 'edit' | 
                'message' | 'github' | 'browser' | 'image' | 'memory_search' | 
                'cron' | 'gateway' | 'sessions_spawn' | 'sessions_list' | 'sessions_show';

interface ToolResult {
  success: boolean;
  data?: unknown;
  error?: string;
  executionId?: string;
}

interface OpenClawInvokeOptions {
  tool: string;
  action?: string;
  args?: Record<string, unknown>;
  sessionKey?: string;
  dryRun?: boolean;
}

interface AgentConfig {
  userId: string;
  engineUrl: string;
  openclawUrl?: string;
  openclawToken?: string;
}

export class OpenClawAgent {
  private client: StateEngineClient;
  private userId: string;
  private sessionId: string = '';
  private activeGoalId: string | null = null;
  private openclawUrl: string;
  private openclawToken: string;

  constructor(config: AgentConfig) {
    this.client = new StateEngineClient({ url: config.engineUrl });
    this.userId = config.userId;
    this.openclawUrl = config.openclawUrl || 'http://127.0.0.1:18789';
    this.openclawToken = config.openclawToken || '';
  }

  /**
   * Initialize the agent - create user and session in Open Engine
   */
  async init(): Promise<void> {
    try {
      await this.client.createUser(this.userId);
      
      const existingSession = await this.client.getActiveSession(this.userId);
      if (existingSession) {
        this.sessionId = existingSession.id;
        const goals = await this.client.listPendingGoals(this.sessionId);
        if (goals.length > 0) {
          this.activeGoalId = goals[0].id;
        }
        console.log(`[OpenClawAgent] Resumed existing session: ${this.sessionId}`);
        await this.replayIncompleteExecutions();
        return;
      }

      const session = await this.client.createSession(this.userId);
      this.sessionId = session.id;

      console.log(`[OpenClawAgent] Initialized: user=${this.userId}, session=${this.sessionId}`);
    } catch (error) {
      console.error('[OpenClawAgent] Init failed:', error);
      throw error;
    }
  }

  /**
   * Resume a specific session by ID
   */
  async resumeSession(sessionId: string): Promise<void> {
    try {
      const session = await this.client.getSession(sessionId);
      this.sessionId = session.id;
      
      const goals = await this.client.listPendingGoals(session.id);
      if (goals.length > 0) {
        this.activeGoalId = goals[0].id;
      }

      console.log(`[OpenClawAgent] Resumed session: ${sessionId}`);
      
      await this.replayIncompleteExecutions();
    } catch (error) {
      console.error('[OpenClawAgent] Resume failed:', error);
      throw error;
    }
  }

  /**
   * Execute a tool with idempotency guarantee
   * 
   * @param toolName - The OpenClaw tool to execute
   * @param params - Tool parameters
   * @param options - Execution options
   */
  async execute(
    toolName: string,
    params: Record<string, unknown> = {},
    options: {
      goalName?: string;
      idempotencyKey?: string;
      priority?: 'low' | 'medium' | 'high';
    } = {}
  ): Promise<ToolResult> {
    try {
      if (!this.sessionId) {
        await this.init();
      }

      if (!this.activeGoalId || options.goalName) {
        const goal = await this.client.createGoal(
          this.userId,
          this.sessionId,
          options.goalName || `Execute ${toolName}`,
          undefined
        );
        this.activeGoalId = goal.id;
      }

      

      const execution = await this.client.executeToolIdempotent(
        this.userId,
        this.sessionId,
        this.activeGoalId,
        toolName,
        params
        // idempotency_key is now auto-generated by the server
      );

      if (execution.status === 'completed' || execution.status === 'running') {
        console.log(`[OpenClawAgent] Reused cached execution: ${execution.id}`);
        return {
          success: execution.status === 'completed',
          data: execution.output,
          executionId: execution.id
        };
      }

      const toolResult = await this.invokeOpenClawTool({
        tool: toolName,
        action: 'json',
        args: params
      });

      if (toolResult.success) {
        await this.client.updateToolExecution({
          ...execution,
          status: 'completed',
          output: toolResult.data as Record<string, unknown>,
          completed_at: new Date().toISOString()
        });
      } else {
        await this.client.updateToolExecution({
          ...execution,
          status: 'failed',
          error: toolResult.error,
          completed_at: new Date().toISOString()
        });
      }

      return {
        success: toolResult.success,
        data: toolResult.data,
        error: toolResult.error,
        executionId: execution.id
      };

    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error'
      };
    }
  }

  /**
   * Invoke a tool via OpenClaw Gateway HTTP API
   */
  private async invokeOpenClawTool(invokeOptions: OpenClawInvokeOptions): Promise<ToolResult> {
    if (!this.openclawToken) {
      return {
        success: false,
        error: 'OpenClaw token not configured'
      };
    }

    try {
      const response = await fetch(`${this.openclawUrl}/tools/invoke`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${this.openclawToken}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          tool: invokeOptions.tool,
          action: invokeOptions.action || 'json',
          args: invokeOptions.args || {},
          sessionKey: invokeOptions.sessionKey || 'main',
          dryRun: invokeOptions.dryRun || false
        }),
      });

      if (!response.ok) {
        return {
          success: false,
          error: `HTTP error: ${response.status} ${response.statusText}`
        };
      }

      const data = await response.json();
      return {
        success: true,
        data
      };
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to invoke OpenClaw tool'
      };
    }
  }

  /**
   * Replay incomplete executions from previous session
   */
  async replayIncompleteExecutions(): Promise<void> {
    if (!this.sessionId) {
      console.log('[OpenClawAgent] No session to replay');
      return;
    }

    try {
      const goals = await this.client.listPendingGoals(this.sessionId);
      
      for (const goal of goals) {
        const executions = await this.client.listToolExecutions(goal.id);
        const incomplete = executions.filter(e => 
          e.status === 'pending' || e.status === 'running'
        );

        for (const exec of incomplete) {
          console.log(`[OpenClawAgent] Replaying incomplete: ${exec.tool_name} (${exec.id})`);
          
          const result = await this.invokeOpenClawTool({
            tool: exec.tool_name,
            action: 'json',
            args: exec.tool_input as Record<string, unknown>
          });

          await this.client.updateToolExecution({
            ...exec,
            status: result.success ? 'completed' : 'failed',
            output: result.success ? result.data as Record<string, unknown> : undefined,
            error: result.error,
            completed_at: new Date().toISOString()
          });
        }
      }
      
      console.log('[OpenClawAgent] Replay complete');
    } catch (error) {
      console.error('[OpenClawAgent] Replay failed:', error);
    }
  }

  /**
   * Get full audit trail of current session
   */
  async getSessionAudit(): Promise<{
    session: Session;
    goals: Goal[];
    executions: ToolExecution[];
  }> {
    if (!this.sessionId) {
      throw new Error('No active session');
    }

    const session = await this.client.getSession(this.sessionId);
    const goals = await this.client.listPendingGoals(this.sessionId);
    const executions: ToolExecution[] = [];
    
    for (const goal of goals) {
      const goalExecutions = await this.client.listToolExecutions(goal.id);
      executions.push(...goalExecutions);
    }

    return { session, goals, executions };
  }

  /**
   * List all sessions for this user
   */
  async listSessions(): Promise<Session[]> {
    return this.client.listSessions(this.userId);
  }

  /**
   * Get all pending goals in current session
   */
  async listPendingGoals(): Promise<Goal[]> {
    if (!this.sessionId) {
      return [];
    }
    return this.client.listPendingGoals(this.sessionId);
  }

  /**
   * Generate deterministic idempotency key from tool + params
   */
  private generateKey(toolName: string, params: Record<string, unknown>): string {
    const paramsHash = JSON.stringify(params);
    return `${toolName}-${Buffer.from(paramsHash).toString('base64').slice(0, 16)}-${Date.now()}`;
  }

  /**
   * Get current session ID
   */
  getSessionId(): string {
    return this.sessionId;
  }

  /**
   * Get current goal ID
   */
  getGoalId(): string | null {
    return this.activeGoalId;
  }
}

export default OpenClawAgent;
